extract = 'total_dyn_inst: (\d+)'
benchmarks = 'benchmarks/*.bril'

[runs.baseline]
pipeline = [
    "bril2json",
    "brili -p {args}",
]

[runs.lesson2]
pipeline = [
    "bril2json",
    "lesson2/transform.py",
    "brili -p {args}",
]
